### ISSUE TITLE
IT Expo demo features needed and bugs

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/mwc_demo#46]
For the most part the bugs/features are listed in the video below

Challenges:

Deleting [HrO2Receiver](https://github.com/atsign-foundation/mwc_demo/blob/trunk/flutter/iot_receiver/lib/models/hro2_receiver.dart) objects

Most important is to delete [HrO2Receiver](https://github.com/atsign-foundation/mwc_demo/blob/trunk/flutter/iot_receiver/lib/models/hro2_receiver.dart) objects

Current method is Hro2DataService.deleteReceiver(HrO2Receiver hrO2Receiver)

Issue currently seems to be in the data.value == hrO2Receiver 

Editing [HrO2Receiver](https://github.com/atsign-foundation/mwc_demo/blob/trunk/flutter/iot_receiver/lib/models/hro2_receiver.dart) objects

The form for creating an [HrO2Receiver](https://github.com/atsign-foundation/mwc_demo/blob/trunk/flutter/iot_receiver/lib/models/hro2_receiver.dart) is [here](https://github.com/atsign-foundation/mwc_demo/blob/trunk/flutter/iot_receiver/lib/forms/receiver_form.dart). The simple approach is to create a new edit receiver form with initial values from a receiver object that can be changed and then update it using the putReceiver(HrO2Receiver hrO2Receiver) method.

https://user-images.githubusercontent.com/6131216/193761262-80fb6c61-3c8a-4ea7-b31e-8318be94c94b.mp4

**Comment by cconstab** [comment]
I now have the ability to delete receivers (yay!) Same pattern can be used for data owners I would think

https://github.com/atsign-foundation/mwc_demo/pull/47  Needs a look and merge

The issue I did have was that I can only add one receiver @nickelskevin this is probably a hang over from big json to atKeys? Just needs a tweek ..

Bed now

**Comment by nitesh2599** [comment]
I have added the feature where we can edit a receiver by clicking on it. 

https://github.com/atsign-foundation/mwc_demo/pull/48

**Comment by sarika01** [comment]
Can a data owner be deleted? I get an error like this after deleting the atsign "anthony":

<img src="https://user-images.githubusercontent.com/12222326/193848278-213c75fb-4a33-464e-9cc5-73316ef68937.png" width=200 height=300/>

**Comment by gkc** [comment]
Marking this as 8SP (GeekyAnts team, Colin time and Kevin time) and closing
